name: CI-poi
env:
  registry: openhacksf39htz4acr.azurecr.io
  repository: devopsoh/api-poi
  docker_path: apis/poi/web
  app_name: openhacksf39htz4poi-staging

on:
  pull_request:
    branches:
    - 'master'
    paths:
    - 'apis/poi/**'
    - '.github/workflows/CI-poi.yml' 
  push:
    branches:
    - 'master'
    paths:
    - 'apis/poi/**'
    - '.github/workflows/CI-poi.yml'

jobs:
  POI-build-and-unittest:

    runs-on: ubuntu-latest

#    if: ${{ github.event_name == 'pull_request' }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      #with:
        #dotnet-version: '3.1.202'
    - name: Install dependencies
      run: dotnet restore apis/poi/web/*.csproj
    
    - name: .NET Build Web
      run: dotnet build --configuration Release --no-restore apis/poi/web/*.csproj
    - name: .NET Build Unit Tests
      run: dotnet build --configuration Release apis/poi/tests/UnitTests/UnitTests.csproj
    - name: .NET Test
      run: dotnet test --no-restore --verbosity normal apis/poi/tests/UnitTests
      
    - uses: JasonEtco/create-an-issue@v2
      if: ${{ failure() }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: .github/ISSUE_TEMPLATE/custom.md
      id: create-issue
    - run: 'echo Created issue number ${{ steps.create-issue.outputs.number }}'
    - run: 'echo Created ${{ steps.create-issue.outputs.url }}'

  docker_build_and_push:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: POI-build-and-unittest
    steps:     
    - uses: actions/checkout@v2
    - name: Docker login
      uses: Azure/docker-login@v1     
      with:
        #ACR name
        username: ${{ secrets.ACR_USERNAME }}
        #ACR password
        password: ${{ secrets.ACR_PASSWORD }}
        #ACR URL
        login-server: ${{ secrets.ACR_SERVER }}
      #run: docker login $registry -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.GITHUBTOKEN }}
    - name: Docker build
      run: docker build -t $registry/$repository:${{github.run_number}} --build-arg build_version=${{github.run_number}} $docker_path
    - name: Docker Push
      run: docker push $registry/$repository:${{github.run_number}}