name: CI-poi

on:
  pull_request:
    branches:
    - 'master'
    paths:
    - 'apis/poi/**'
    - '.github/workflows/CI-poi.yml' 
  push:
    branches:
    - 'master'
    paths:
    - 'apis/poi/**'
    - '.github/workflows/CI-poi.yml'

jobs:
  POI-build-and-unittest:

    runs-on: ubuntu-latest

    if: ${{ github.event_name == 'pull_request' }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      #with:
        #dotnet-version: '3.1.202'
    - name: Install dependencies
      run: dotnet restore apis/poi/web/*.csproj
    
    - name: .NET Build Web
      run: dotnet build --configuration Release --no-restore apis/poi/web/*.csproj
    - name: .NET Build Unit Tests
      run: dotnet build --configuration Release apis/poi/tests/UnitTests/UnitTests.csproj
    - name: .NET Test
      run: dotnet test --no-restore --verbosity normal apis/poi/tests/UnitTests
      
    - uses: JasonEtco/create-an-issue@v2
      if: ${{ failure() }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: .github/ISSUE_TEMPLATE/custom.md
      id: create-issue
    - run: 'echo Created issue number ${{ steps.create-issue.outputs.number }}'
    - run: 'echo Created ${{ steps.create-issue.outputs.url }}'

  POI-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@master

      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
            inlineScript: |
              echo "Building API-POI image..."
              echo "Changing directory to /apis/poi/web..."
              cd "./apis/poi/web"
              az acr build --image "devopsoh/api-poi:${{ env.GITHUB_RUN_ID }}" --registry ${{ secrets.ACR_USERNAME }} --file Dockerfile .
      - name: 'Deploy to Azure Web App for Container'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'openhack25g1cxh1poi-staging'
          images: ${{ secrets.ACR_SERVER }}/devopsoh/api-poi:${{ env.GITHUB_RUN_ID }}